### ISSUE TITLE
Uncaught Error: Notification must be created with string message: Error: ENOTDIR: not a directory...

### ISSUE THREAD

**Issue by AlanForester** [sdinesh86/meteor-assist#1]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.19
**System**: Mac OS X 10.11
**Thrown From**: [meteor-assist](https://github.com/sdinesh86/meteor-assist) package, v0.1.0
### Stack Trace

Uncaught Error: Notification must be created with string message: Error: ENOTDIR: not a directory, mkdir '/Users/alex/Documents/Projects/ExampleMyProjectMeteor/ExampleMyProjectMeteor.html/qws'

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/notification.js:25

Error: Notification must be created with string message: Error: ENOTDIR: not a directory, mkdir '/Users/alex/Documents/Projects/ExampleMyProjectMeteor/ExampleMyProjectMeteor.html/qws'
  at Notification.module.exports.Notification.validate (/Applications/Atom.app/Contents/Resources/app.asar/src/notification.js:25:15)
  at new Notification (/Applications/Atom.app/Contents/Resources/app.asar/src/notification.js:20:12)
  at NotificationManager.module.exports.NotificationManager.addError (/Applications/Atom.app/Contents/Resources/app.asar/src/notification-manager.js:41:35)
  at MeteorAssistEditorView.module.exports.MeteorAssistEditorView.onConfirm (/Users/alex/.atom/packages/meteor-assist/lib/meteor-assist-view.coffee:133:26)
  at atom-text-editor.MeteorAssistEditorView.atom.commands.add.core:confirm (/Users/alex/.atom/packages/meteor-assist/lib/meteor-assist-view.coffee:27:14)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:245:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:184:20)

```
### Commands

```
  2x -1:59.4.0 autocomplete-plus:activate (atom-text-editor.editor.is-focused)
     -1:57.5.0 snippets:expand (atom-text-editor.editor.is-focused)
     -1:56.4.0 core:undo (atom-text-editor.editor.is-focused)
     -1:55.6.0 autocomplete-plus:activate (atom-text-editor.editor.is-focused)
     -1:55.5.0 snippets:expand (atom-text-editor.editor.is-focused)
     -1:54.8.0 core:undo (atom-text-editor.editor.is-focused)
     -1:54 autocomplete-plus:activate (atom-text-editor.editor.is-focused)
  2x -1:38.9.0 symbols-view:toggle-file-symbols (ul.list-inline.tab-bar.inset-panel)
     -1:32.4.0 term3:open (atom-pane.pane.active)
     -1:29.7.0 core:backspace (div.terminal)
  2x -1:29.1.0 core:confirm (div.terminal)
```
### Config

``` json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "base16-tomorrow-dark-theme"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-ternjs, v0.8.1
meteor-api, v2.20.0
meteor-assist, v0.1.0
term3, v0.13.0

# Dev
No dev packages
```

**Comment by sdinesh86** [comment]
Hello @AlexCollin 

Can you please give more details on how to reproduce, I tried reproducing it but it doesnt seem to happening on mu side

also I cannot check it on Mac since I am a windows user, but i will try to check it and will get back
